In [1]:
import copy, math
import numpy as np
import matplotlib.pyplot as plt
#plt.style.use('./deeplearning.mplstyle')
np.set_printoptions(precision=2)  

In [2]:
X_train = np.array([[2104, 5, 1, 45], [1416, 3, 2, 40], [852, 2, 1, 35]])
y_train = np.array([460, 232, 178])

b_init = 785.1811367994083
w_init = np.array([ 0.39133535, 18.75376741, -53.36032453, -26.42131618])


print(f"X Shape: {X_train.shape}, X Type:{type(X_train)})")
print(X_train)
print(f"y Shape: {y_train.shape}, y Type:{type(y_train)})")
print(y_train)
print(f"w_init shape: {w_init.shape}, b_init type: {type(b_init)}")

X Shape: (3, 4), X Type:<class 'numpy.ndarray'>)
[[2104    5    1   45]
 [1416    3    2   40]
 [ 852    2    1   35]]
y Shape: (3,), y Type:<class 'numpy.ndarray'>)
[460 232 178]
w_init shape: (4,), b_init type: <class 'float'>


In [3]:
#single price y^ prediction Loop non vector:
x=X_train[0]
n=x.shape[0]
print (n)
p=0.0
for i in range(n):
    p_i=w_init[i]*x[i]
    p=p+p_i

p=p+b_init
print(p)

4
459.9999976194083


In [4]:
#single price y^ prediction Loop vector:
p=np.dot(X_train[0],w_init)
p=p+b_init
print(p)

459.9999976194083


In [5]:
#compute Cost J(w,b)
m= X_train.shape[0] # .shape gives (3,4), 3 is m
cost=0.0
for i in range(m):
    #cost= cost+ (((np.dot(X_train[i],w_init))+b_init)-y_train[i])**2
    fwb=np.dot(X_train[i],w_init)+b_init
    cost=cost+(fwb -y_train[i])**2
cost=cost/(2*m)
print(cost)


1.5578904428966628e-12


In [ ]:
#Gradient Descent:
#print(X_train.shape) #.shape gives (3,4) 3 is m, and 4 is n, number of features
#print(X_train[0,0])
alpha = 5.0e-7
w=w_init.shape[0]
w_temp = np.copy(w_init)
#print(f"temp:  {w_temp}")
m,n=X_train.shape
djdw=np.zeros((m,)) # better to write with double parenthesis n,
djdb=0
print(djdw)
err=0

for j in range(n):
    for i in range(m):
        err=(np.dot(w_init ,X_train[i])+b_init)-y_train[i]
        #djdb=djdb+err
        err=err*X_train[i,j]
        djdw[i]=err
    w_sum=np.sum(djdw)
    w_temp[j]=w_temp[j]-alpha*(w_sum/m)

for i in range(m):
        err=(np.dot(w_init ,X_train[i])+b_init)-y_train[i]
        djdb=djdb+err   

b_init=b_init-alpha*(djdb/m)    
w_init=np.copy(w_temp)
    


temp:  [  0.39  18.75 -53.36 -26.42]
[0. 0. 0. 0.]


-0.005017928478309841