In [1]:
import copy, math
import numpy as np
import matplotlib.pyplot as plt
#plt.style.use('./deeplearning.mplstyle')
np.set_printoptions(precision=2)  

In [2]:
X_train = np.array([[2104, 5, 1, 45], [1416, 3, 2, 40], [852, 2, 1, 35]])
y_train = np.array([460, 232, 178])

print(f"X Shape: {X_train.shape}, X Type:{type(X_train)})")
print(X_train)
print(f"y Shape: {y_train.shape}, y Type:{type(y_train)})")
print(y_train)

X Shape: (3, 4), X Type:<class 'numpy.ndarray'>)
[[2104    5    1   45]
 [1416    3    2   40]
 [ 852    2    1   35]]
y Shape: (3,), y Type:<class 'numpy.ndarray'>)
[460 232 178]


In [3]:
b_init = 785.1811367994083
w_init = np.array([ 0.39133535, 18.75376741, -53.36032453, -26.42131618])
print(f"w_init shape: {w_init.shape}, b_init type: {type(b_init)}")

w_init shape: (4,), b_init type: <class 'float'>


In [ ]:
#single price y^ prediction Loop non vector:
x=X_train[0]
n=x.shape[0]
print (n)
p=0.0
for i in range(n):
    p_i=w_init[i]*x[i]
    p=p+p_i

p=p+b_init
print(p)

4
459.9999976194083


In [ ]:
#single price y^ prediction Loop vector:
p=np.dot(X_train[0],w_init)
p=p+b_init
print(p)

459.9999976194083


In [40]:
#compute Cost J(w,b)
m= X_train.shape[0] # .shape gives (3,4), 3 is m
cost=0.0
for i in range(m):
    #cost= cost+ (((np.dot(X_train[i],w_init))+b_init)-y_train[i])**2
    fwb=np.dot(X_train[i],w_init)+b_init
    cost=cost+(fwb -y_train[i])**2
cost=cost/(2*m)
print(cost)


1.5578904428966628e-12
